//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyplamForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPLAN
    {
        public int ID { get; set; }
        public System.DateTime NGAY { get; set; }
        public string DP { get; set; }
        public int TIMES { get; set; }
        public bool FINISH { get; set; }
    }
}
